<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKptd0ip\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKptd0ip/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKptd0ip.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKptd0ip\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKptd0ip\appProdProjectContainer([
    'container.build_hash' => 'Kptd0ip',
    'container.build_id' => 'a65292bd',
    'container.build_time' => 1666979539,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKptd0ip');
