<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUow04rj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUow04rj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUow04rj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUow04rj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUow04rj\appProdProjectContainer([
    'container.build_hash' => 'Uow04rj',
    'container.build_id' => '678d6f2b',
    'container.build_time' => 1667224498,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUow04rj');
