version: "3"
networks:
    demoprestashop-net:
      driver: bridge
services:
    mysql:
        image: demoprestashop-bd
        container_name: demoprestashop-bd
        tty: true
        ports:
            - "4206:3306"
        volumes:
            - "./contenedor/lib/mysql/:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=prestashop
            - MYSQL_DATABASE=prestashop
        networks:
            - demoprestashop-net
    server:
        image: demoprestashop
        working_dir: /src
        container_name: demoprestashop
        ports:
            - "4280:80"
        volumes:
            - "./:/src"
        environment:
            APACHE_DOCUMENT_ROOT: /src
            #DB_SERVER: demoprestashop-bd
        depends_on:
            - mysql
        networks:
            - demoprestashop-net